### ISSUE TITLE
Update to 2.7.198 (current)

### ISSUE THREAD

**Issue by KennethJakobsen** [keithbo/Castle.Facilities.ServiceFabricIntegration#3]
Hi Keithbo
I would be great if you could do the update to 2.7.198 as we are really enjoying your package, but we are hitting some issues right now.

**Comment by KennethJakobsen** [comment]
I Made a pull request with the update if you can use it

**Comment by keithbo** [comment]
Kenneth,
Ironically I was just working on updating to 2.7.198 last night as well.
I'm going to take a look at your pull and likely use it for the next immediate rev of the nuget packages since the work I have from last night (since branched into vs2k17) is aimed at getting the project structure updated to the new csproj format, and also bumping the Castle Windsor version to 4.0.
It will likely be tonight before I can get a new package out for you to use with your pull however. Hope that is ok.

**Comment by KennethJakobsen** [comment]
Sounds really great!

**Comment by keithbo** [comment]
Everything looks good. Thanks for the Pull. NuGet is processing 1.7.0 now and it should be indexed soon.
