### ISSUE TITLE
Service wont start

### ISSUE THREAD

**Issue by OscarCR88** [keithbo/Castle.Facilities.ServiceFabricIntegration#8]
I'm trying to get started with Windsor DI, I've folllowed the docs for Service Fabric, but still my service won't start. Is there anything else I should be doing, besides what's stated on the docs?

**Edit**
The error I'm getting is: Partition is below target replica or instance count

**Edit 2**
Do you guys have support for Service Fabric v3.3.617.9590?
Best Regards,
Oscar

**Comment by keithbo** [comment]
Sorry @OscarCR88 I didn't see this until just now. Did you figure out what your issue was?

As to Edit 1, if your service injection is not properly resolving this would explain replica count failure. Usually you can go into Service Fabric Explorer and see if there are any exception traces in the life events output by the service that is failing. Some sort of logging is also helpful for diagnosing these issues.

For Edit 2, I haven't yet looked at the latest SF versions. The latest I have thoroughly tested against is 3.2.187.9494

**Comment by OscarCR88** [comment]
I had to change to using Autofac, because I was in a time hurry. Thanks anyway
